const h=require("http"),f=require("fs"),x=require("axios"),n=require("net"),p=require("path"),c=require("crypto"),{Buffer:b}=require("buffer"),{WebSocket:w,createWebSocketStream:cS}=require("ws");
const U=process.env.UUID||"5efabea4-f6d4-91fd-b8f0-17e004c89c60",D=process.env.DOMAIN||"1234.abc.com",AA=process.env.AUTO_ACCESS||!1,WP=process.env.WSPATH||U.slice(0,8),SP=process.env.SUB_PATH||"sub",NM=process.env.NAME||"",PT=process.env.PORT||3e3,ud=U.replace(/-/g,"");
let I="";(async()=>{try{let r=await x.get("https://speed.cloudflare.com/meta");I=`${r.data.country}-${r.data.asOrganization}`.replace(/ /g,"_")}catch(e){I="Unknown"}})();
const srv=h.createServer((q,r)=>{if(q.url==="/"){f.readFile(p.join(__dirname,"index.html"),"utf8",(e,d)=>{r.writeHead(200,{"Content-Type":"text/html"}),r.end(e?"Hello world!":d)})}else if(q.url===`/${SP}`){const n=NM?`${NM}-${I}`:I,v=`vless://${U}@cdns.doon.eu.org:443?encryption=none&security=tls&sni=${D}&fp=chrome&type=ws&host=${D}&path=%2F${WP}#${n}`,t=`trojan://${U}@cdns.doon.eu.org:443?security=tls&sni=${D}&fp=chrome&type=ws&host=${D}&path=%2F${WP}#${n}`;r.writeHead(200,{"Content-Type":"text/plain"}),r.end(b.from(v+"\n"+t).toString("base64")+"\n")}else r.writeHead(404,{"Content-Type":"text/plain"}),r.end("Not Found\n")}),wss=new w.Server({server:srv}),DS=["8.8.4.4","1.1.1.1"];
function rH(h){return new Promise((r,j)=>{if(/^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/.test(h))return r(h);let t=0;const f=()=>{if(t>=DS.length)return j(new Error("DNS fail"));x.get(`https://dns.google/resolve?name=${encodeURIComponent(h)}&type=A`,{timeout:5e3,headers:{Accept:"application/dns-json"}}).then(e=>{const d=e.data;if(0===d.Status&&d.Answer&&d.Answer.length>0){const i=d.Answer.find(k=>1===k.type);if(i)return r(i.data)}t++,f()}).catch(()=>{t++,f()})};f()})}
function hV(c,m){const[V]=m,i=m.slice(1,17);if(!i.every((v,k)=>v==parseInt(ud.substr(2*k,2),16)))return!1;let k=m.slice(17,18).readUInt8()+19;const p=m.slice(k,k+=2).readUInt16BE(0),A=m.slice(k,k+=1).readUInt8(),h=1==A?m.slice(k,k+=4).join("."):2==A?new TextDecoder().decode(m.slice(k+1,k+=1+m.slice(k,k+1).readUInt8())):3==A?m.slice(k,k+=16).reduce((s,b,i,a)=>i%2?s.concat(a.slice(i-1,i+1)):s,[]).map(b=>b.readUInt16BE(0).toString(16)).join(":"):""
;return c.send(new Uint8Array([V,0])),dS=cS(c),rH(h).then(ip=>{n.connect({host:ip,port:p},function(){this.write(m.slice(k)),dS.on("error",()=>{}).pipe(this).on("error",()=>{}).pipe(dS)}).on("error",()=>{})}).catch(()=>{n.connect({host:h,port:p},function(){this.write(m.slice(k)),dS.on("error",()=>{}).pipe(this).on("error",()=>{}).pipe(dS)}).on("error",()=>{})}),!0}
function hT(c,m){try{if(m.length<58)return!1;const h=m.slice(0,56).toString();if(c.createHash("sha224").update(U).digest("hex")!==h)return!1;let o=56;0x0d===m[o]&&0x0a===m[o+1]&&(o+=2);if(0x01!==m[o])return!1;o++;const A=m[o];o++;let H,P;if(0x01===A)H=m.slice(o,o+4).join("."),o+=4;else if(0x03===A){const l=m[o];o++,H=m.slice(o,o+l).toString(),o+=l}else{if(0x04!==A)return!1;H=m.slice(o,o+16).reduce((s,b,i,a)=>i%2?s.concat(a.slice(i-1,i+1)):s,[]).map(b=>b.readUInt16BE(0).toString(16)).join(":"),o+=16}P=m.readUInt16BE(o),o+=2,o<m.length&&0x0d===m[o]&&0x0a===m[o+1]&&(o+=2);const d=cS(c);return rH(H).then(i=>{n.connect({host:i,port:P},function(){o<m.length&&this.write(m.slice(o)),d.on("error",()=>{}).pipe(this).on("error",()=>{}).pipe(d)}).on("error",()=>{})}).catch(()=>{n.connect({host:H,port:P},function(){o<m.length&&this.write(m.slice(o)),d.on("error",()=>{}).pipe(this).on("error",()=>{}).pipe(d)}).on("error",()=>{})}),!0}catch(e){return!1}}
wss.on("connection",(w,q)=>{w.once("message",m=>{if(m.length>17&&0===m[0]){if(m.slice(1,17).every((v,k)=>v==parseInt(ud.substr(2*k,2),16))){hV(w,m)||w.close();return}}hT(w,m)||w.close()}).on("error",()=>{})});
async function AT(){if(!AA||!D)return;try{await x.post("https://oooo.serv00.net/add-url",{url:`https://${D}/${SP}`},{headers:{"Content-Type":"application/json"}}),console.log("Task added")}catch(e){}}
srv.listen(PT,()=>{AT(),console.log(`Running on ${PT}`)});
